### PR TITLE
Refactor tests and remove hints to better visualize success/failure

### PR DESCRIPTION
**Pull request by dlesnoff**
The for loop on the list of file names is more readable.
I added hints:off compilation option, to remove superfluous information for the tests. (Similarly to [bigints](https://github.com/nim-lang/bigints/blob/master/bigints.nimble))

To be consistent in syntax, I can do the same for documentation building.

### CODE REVIEW

**Review by pietroppeter — APPROVED** [review]
Looks good to me!

**Review by HugoGranstrom — APPROVED** [review]
Nice, a well needed refactor that wet should probably do for the docs as well as you said.

**Comment by pietroppeter** [comment]
> There is an issue with numericalnim which gets in the way when building numerical.nim so I removed it from the list.
> I mentioned some of the specific dependencies I had to install (due to imports in the documentation) in a comment.
> It would be nice if this task activates extra requirements so that nimble can do the proper installations automatically.

Not that there is already a task docdeps that specifies which version of the libraries are needed to build the docs. As such there is no need for an extra comment to mention dependencies, nor I think there is a need to remove numerical from docs.

**Comment by dlesnoff** [comment]
I reverted last commit since I did not see that extra task.
I removed numerical to build other docs, since it stops at the very first build failure.

**Comment by HugoGranstrom** [comment]
The problem with numerical.nim is that it uses an old version of numericalnim. If you have a more recent version installed it will use that instead and it will fail to compile. I think it is the `NumContext[float]` that should be `NumContext[float, float]` for it to work with the latest numericalnim.

**Comment by dlesnoff** [comment]
I reverted the numericalnim changes.

**Comment by pietroppeter** [comment]
Thanks again!

**Comment by dlesnoff** [comment]
You are welcome!

**Pull request merged**
