### PR TITLE
add hlHtml to nimiBoost

### PR DESCRIPTION
**Pull request by HugoGranstrom**
Adds HTML-highlighting support through nimiBoost

### CODE REVIEW

**Comment by pietroppeter** [comment]
good for me, I just noticed that the mention of nimiboost in readme/index is:

```
The vs code extension [nimiboost](https://marketplace.visualstudio.com/items?itemName=hugogranstrom.nimiboost) provides markdown highlighting in nimib file and a preview mechanism.
```

Maybe it is worth mentioning formats other than markdown or reformulating that in another way (not sure how clear that sentence is for anyone that does not know what it means). Or maybe we update it later when we will add the link to Nimiboost livecoding video. ;)

**Comment by HugoGranstrom** [comment]
Good catch, I've tried to improve it a bit. But it will be much easier after NimConf when we have a video to link to that shows what it can do. :)

**Comment by pietroppeter** [comment]
Mmh, did you change in readme manually? We are still with index generated readme (will be removed), so changes should happen in index.nim and there should be a nimble task to update the readme. Other than that wording is much improved

**Comment by HugoGranstrom** [comment]
Changed index.nim and ran `nimble readme`.

**Comment by pietroppeter** [comment]
Ah ok, looking at the diffs I saw more changes in the readme than in index. Checking better I realize that last time we fixed nbCodeFromJs -> nbJsToCode the readme was not rerun and changes came out now. :)

Merging, thanks!

**Comment by pietroppeter** [comment]
Ah ok, looking at the diffs I saw more changes in the readme than in index. Checking better I realize that last time we fixed nbCodeFromJs -> nbJsToCode the readme was not rerun and changes came out now. :)

Merging, thanks!

**Pull request merged**
