### PR TITLE
release 0.3.2

### PR DESCRIPTION
**Pull request by pietroppeter**
- [x] update changelog
- [x] bump version to 0.3.2

### CODE REVIEW

**Comment by pietroppeter** [comment]
anything else we need @HugoGranstrom? any update of dependencies or other stuff that I am forgetting?

**Comment by HugoGranstrom** [comment]
The tests are green, and the nimble version is bumped, so: go for it! :smile:

**Comment by pietroppeter** [comment]
honestly changelog looks a bit redundant if we have a good title for a PR, see: https://github.com/pietroppeter/nimib/releases/tag/v0.3.2

**Comment by HugoGranstrom** [comment]
Haha yes at least for these smaller releases which doesn't need any further explaination. For big releases I think it makes a lot of sense to include it though.

**Pull request merged**
