### PR TITLE
rerun nimble readme

### PR DESCRIPTION
**Pull request by pietroppeter**
forgot to rerun `nimble readme` at the end of #103

### CODE REVIEW

**Comment by HugoGranstrom** [comment]
The example usage code-block just says `discard` now, even though it should be overridden by `hello` :see_no_evil:

**Comment by pietroppeter** [comment]
what do you mean, I should actually check what I am merging before merging!? 😝

**Comment by pietroppeter** [comment]
although to be honest this was a bug that was already there last commit...

**Comment by HugoGranstrom** [comment]
> what do you mean, I should actually check what I am merging before merging!? 😝

🤣 No that would be too much 🤪
And yes it was from the small md refactor probably. 

If it wasn't for the fact that the readme soon will be independent from index.nim I would have proposed to add it to the preview somehow 🤭

**Comment by pietroppeter** [comment]
> 🤦‍♂️ I'll go drag something old over myself 🤣

I gotta ask, never heard of this expression, is it possibly derived from Swedish? 🧐

**Comment by HugoGranstrom** [comment]
I looked it up and yes it seems like it's not used in English 😅 after a bit of googling if found the English idiom "I'll sink through the floor" which is somewhat equivalent, you are embarrassed so you want to hide. In the Swedish case you hide under something old for some reason 😳

**Comment by pietroppeter** [comment]
ah, nice! In italian it would be "sprofondare dalla vergogna" which would literally be translated as "sink in shame".

**Pull request merged**
