### PR TITLE
Add `nbCodeSkip` and `allblocks.nim`

### PR DESCRIPTION
**Pull request by neroist**
Add `nbCodeSkip` from #183

### CODE REVIEW

**Comment by neroist** [comment]
On the same fork I also added `nbCapture` (branch `nb-capture`), but I want to add a pull request for that after this one has been merged.

**Comment by HugoGranstrom** [comment]
First and foremost, thank you so much for contributing to nimib! :smile: It was a pleasant surprise to see a PR from a new face. 

As for the code it looks good, the only thing missing (as per the [CONTRIBUTING.md](https://github.com/pietroppeter/nimib/blob/main/CONTRIBUTING.md)) is to
- [ ] add a basic test to [tests/tnimib.nim](https://github.com/pietroppeter/nimib/blob/main/tests/tnimib.nim) 
- [ ] mention it in the readme
- [ ] Showcase it somewhere in the documentation. Not sure exactly where though, we are open to suggestions. Maybe we can create a new document that is simply called `showcase.nim` where we drop showcases of blocks?

**Comment by pietroppeter** [comment]
> Showcase it somewhere in the documentation. Not sure exactly where though, we are open to suggestions. Maybe we can create a new document that is simply called showcase.nim where we drop showcases of blocks?

Yep I think we should have something like that. I propose an `allblocks.nim` document where we have a brief description and example for all blocks. In this PR you could add just an example for this single block and we will have a separate issue/PR to populate it with the rest of blocks and think how we can structure that better

**Comment by HugoGranstrom** [comment]
Awesome! If you are happy with this PR I'm ready to merge it :D

**Comment by neroist** [comment]
Okay, I'm happy with it! It's okay to merge.

**Pull request merged**
