### PR TITLE
Fix CI: upload-artifacts

### PR DESCRIPTION
**Pull request by HugoGranstrom**
It's due time we try to fix the preview in the CI

### CODE REVIEW

**Comment by HugoGranstrom** [comment]
Strange, I can't reproduce the error locally :/

**Comment by HugoGranstrom** [comment]
@quimt do you have any ideas what might be going on?

**Comment by quimt** [comment]
> @quimt do you have any ideas what might be going on?

I don't know in detail, but happyx does use macros to produce [emit pragmas](https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-emit-pragma). I haven't encountered this bug using happyx by itself, so I suspect it has something to do with how happyx interacts with nimib's protocol for sandboxing the code. Whatever the reason, emiting something other than a string doesn't make sense as far as I know.

**Comment by HugoGranstrom** [comment]
> I don't know in detail, but happyx does use macros to produce [emit pragmas](https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-emit-pragma). I haven't encountered this bug using happyx by itself, so I suspect it has something to do with how happyx interacts with nimib's protocol for sandboxing the code. Whatever the reason, emiting something other than a string doesn't make sense as far as I know.

Thanks for the leads :D Judging from the error message and this code: https://github.com/HapticX/happyx/blob/3b1d08aaed757cd1747c50a5f1d480444fa18b20/src/happyx/private/macro_utils.nim#L1065
It seems like whatever `args[1][0]` is, it isn't what is't supposed to be. I'll continue digging.

**Comment by HugoGranstrom** [comment]
Ahh, the changes I make to the CI files aren't run... So I will have to merge the changes and just hope it works and then test it with a new PR 🙈

**Pull request merged**
